---
minio_root_user: "{{ vault_minio_root_user }}"
minio_root_password: "{{ vault_minio_root_password }}"

# Harbor host Docker configuration
docker_users: []
docker_insecure_registries:
  - "harbor.nplan.local:80"
