---
# Main Kubernetes
- name: Configure Harbor pull secret on Main Kubernetes
  hosts: devops_nodes
  become: false

  roles:
    - role: harbor_pull_secret
      vars:
        harbor_kubectl_command: "kubectl"

# DR k3s
- name: Configure Harbor pull secret on DR k3s
  hosts: k3s_nodes
  become: true

  roles:
    - role: harbor_pull_secret
      vars:
        harbor_kubectl_command: "/usr/local/bin/k3s kubectl"
